apiVersion: v1
kind: Service
metadata:
    name: nginx-cluster
spec:
    type: ClusterIP
    externalIPs:
        - 192.168.3.254
    ports:
        - name: "http-port"
    ports:
        - name: "http-port"
          protocol: "TCP"
          port: 80
          targetPort: 80
    selector:
        app: nginx-dp
